Registration banner fixes
STEMPremier/celula pull request #128
Opened 2022-01-28 16:51 UTC by wdrescher

* Reopen messages when the text / type changes
* Adjust checkbox label color
* close modal when the actionFn returns true
* pad table cells

2022-01-28 17:55 UTC, warrensplayer requested changes

2022-01-28 17:55 UTC, warrensplayer commented on src/components/form-controls/core/selectable/selectable.less
> +
The default color both checkbox and radio button labels should be @primary-text .  No need for the additional class, just change it above on line 203

2022-01-28 17:55 UTC, warrensplayer commented on src/components/modal/Modal.jsx
> +   * The function should return `true` when the user would like the modal close after action
```suggestion
   * Return `true` to close the modal
```

2022-01-28 17:55 UTC, warrensplayer commented on src/components/table/table.less
> +          padding-right: 2rem;
See what adding some padding all the way around looks like instead of just on the right.

2022-01-28 17:55 UTC, warrensplayer commented on src/components/form-controls/checkbox/Checkbox.jsx
> +      <label className="checkbox" htmlFor={id}>{label}</label>
No need for this new `className`.  See comment in selectable.less

2022-01-28 17:55 UTC, warrensplayer commented on src/components/alert/Alert.jsx
> +  useEffect(() => { setIsVisible(true); }, [type, text]);
Not sure if this fix will work for the scenario I found.  In my scenario, saving the registration banner failed a backend check to make sure the key was unique.  The error from the backend triggered the alert.  If you closed the alert, and then hit save again and got the same error message, the alert would not show again.  In that case, the `type` and `text` of the error would not be different, so I do not think the `useEffect` would trigger.  I am going to think about ways to test this.  Let me know if you have any ideas.

2022-01-28 18:41 UTC, wdrescher commented on src/components/table/table.less
> +          padding-right: 2rem;
It already has a margin bottom and top, and if there is a left padding it won't line up with the title

2022-02-01 02:41 UTC, warrensplayer approved these changes

2022-02-01 02:42 UTC, merged